// src/components/charts/label-count-bar-chart.svelte
<script lang="ts">
  import type { LabelCount } from "@/lib/movie-chart-stats";
  import MovieTooltipPanel from "./movie-tooltip-panel.svelte";
  import { getRoundedBarPath } from "./static-chart-utils";

  export let data: LabelCount[] = [];
  export let emptyLabel = "No chart data yet.";
  export let scrollable = false;

  type TooltipData = LabelCount & {
    x: number;
    y: number;
  };

  let hoverTooltip: TooltipData | null = null;
  let pinnedTooltip: LabelCount | null = null;
  let container: HTMLDivElement;

  const width = 640;
  const rowHeight = 28;
  const labelWidth = 132;
  const rightPadding = 34;

  $: chartHeight = scrollable ? Math.max(300, data.length * rowHeight) : 300;
  $: maxCount = Math.max(...data.map((item) => item.count), 0);

  function truncateLabel(label: string) {
    return label.length > 18 ? `${label.slice(0, 17)}...` : label;
  }

  function activateTooltip(item: LabelCount, event: PointerEvent) {
    const rect = container.getBoundingClientRect();

    hoverTooltip = {
      ...item,
      x: event.clientX - rect.left,
      y: event.clientY - rect.top,
    };
  }
</script>

{#if data.length === 0}
  <div class="flex h-[300px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
    {emptyLabel}
  </div>
{:else}
  <div class="relative" bind:this={container} on:pointerleave={() => (hoverTooltip = null)}>
    <div class={scrollable ? "h-[300px] overflow-y-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" : undefined}>
      <svg class="w-full overflow-visible" style={`height: ${chartHeight}px`} viewBox={`0 0 ${width} ${chartHeight}`} role="img" aria-label="Label count chart" preserveAspectRatio="none">
        {#each data as item, index}
          {@const y = index * rowHeight + 4}
          {@const barWidth = maxCount > 0 ? (item.count / maxCount) * (width - labelWidth - rightPadding) : 0}
          <g>
            <title>{item.label}: {item.count.toLocaleString()} {item.count === 1 ? "movie" : "movies"}</title>
            <text x="0" y={y + 17} class="fill-[var(--muted-foreground)] text-xs">{truncateLabel(item.label)}</text>
            <path
              d={getRoundedBarPath(labelWidth, y + 3, barWidth, 16, 2)}
              fill="var(--chart-5)"
              class="cursor-pointer opacity-90 hover:opacity-100"
              on:pointerenter={(event) => activateTooltip(item, event)}
              on:pointermove={(event) => activateTooltip(item, event)}
              on:click={() => (pinnedTooltip = item)}
            />
            <text x={labelWidth + barWidth + 8} y={y + 16} class="fill-[var(--foreground)] text-xs tabular-nums">{item.count}</text>
          </g>
        {/each}
      </svg>
    </div>

    {#if hoverTooltip && !pinnedTooltip}
      <div
        class="pointer-events-none absolute z-10 max-w-[min(20rem,calc(100%-1rem))] -translate-y-[calc(100%+0.5rem)]"
        style={`left: clamp(0.5rem, ${hoverTooltip.x}px, calc(100% - 20rem)); top: ${hoverTooltip.y}px;`}
      >
        <MovieTooltipPanel title={hoverTooltip.label} count={hoverTooltip.count} movies={hoverTooltip.movies} />
      </div>
    {/if}

    {#if pinnedTooltip}
      <div class="absolute right-2 top-2 z-10 max-w-[calc(100%-1rem)]">
        <MovieTooltipPanel
          title={pinnedTooltip.label}
          count={pinnedTooltip.count}
          movies={pinnedTooltip.movies}
          pinned
          onClose={() => (pinnedTooltip = null)}
        />
      </div>
    {/if}
  </div>
{/if}

// src/components/charts/label-count-bar-chart.tsx
"use client";

import { useState } from "react";
import { Bar, BarChart, CartesianGrid, LabelList, XAxis, YAxis } from "recharts";

import {
  getActiveChartDataIndex,
  MovieListTooltip,
  PinnedMovieListTooltipOverlay,
  type PinnedMovieListTooltip,
} from "@/components/charts/movie-list-tooltip";
import {
  ChartContainer,
  ChartTooltip,
  type ChartConfig,
} from "@/components/ui/chart";
import type { LabelCount } from "@/lib/movie-chart-stats";

const chartConfig = {
  count: {
    label: "Movies",
    color: "var(--chart-5)",
  },
} satisfies ChartConfig;

type LabelCountBarChartProps = {
  data: LabelCount[];
  emptyLabel: string;
  scrollable?: boolean;
};

function truncateLabel(label: string) {
  return label.length > 18 ? `${label.slice(0, 17)}...` : label;
}

export function LabelCountBarChart({
  data,
  emptyLabel,
  scrollable = false,
}: LabelCountBarChartProps) {
  const [pinnedTooltip, setPinnedTooltip] =
    useState<PinnedMovieListTooltip | null>(null);
  const chartHeight = scrollable ? Math.max(300, data.length * 28) : 300;

  if (data.length === 0) {
    return (
      <div className="flex h-[300px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
        {emptyLabel}
      </div>
    );
  }

  return (
    <div className="relative">
      <div
        className={
          scrollable
            ? "h-[300px] overflow-y-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
            : undefined
        }
      >
        <ChartContainer
          config={chartConfig}
          className="w-full aspect-auto"
          style={{ height: chartHeight }}
        >
          <BarChart
            data={data}
            layout="vertical"
            margin={{ top: 4, right: 28, left: 4, bottom: 0 }}
            onClick={(chartState) => {
              const index = getActiveChartDataIndex(chartState, data.length);

              if (index == null) {
                return;
              }

              const item = data[index];
              setPinnedTooltip({
                key: item.label,
                title: item.label,
                count: item.count,
                movies: item.movies,
              });
            }}
          >
            <CartesianGrid horizontal={false} strokeDasharray="2 4" />
            <XAxis type="number" hide allowDecimals={false} />
            <YAxis
              dataKey="label"
              type="category"
              tickLine={false}
              axisLine={false}
              width={118}
              tickFormatter={truncateLabel}
            />
            <ChartTooltip
              active={pinnedTooltip ? false : undefined}
              cursor={false}
              isAnimationActive={false}
              content={
                <MovieListTooltip singularLabel="movie" pluralLabel="movies" />
              }
            />
            <Bar
              dataKey="count"
              fill="var(--color-count)"
              isAnimationActive={false}
              radius={2}
            >
              <LabelList
                dataKey="count"
                position="right"
                className="fill-[var(--foreground)] text-xs tabular-nums"
              />
            </Bar>
          </BarChart>
        </ChartContainer>
      </div>
      <PinnedMovieListTooltipOverlay
        tooltip={pinnedTooltip}
        singularLabel="movie"
        pluralLabel="movies"
        onClose={() => setPinnedTooltip(null)}
      />
    </div>
  );
}
