// src/components/charts/movie-money-over-time-chart.tsx
"use client";

import { useState } from "react";
import {
  CartesianGrid,
  Line,
  LineChart,
  XAxis,
  YAxis,
} from "recharts";

import type { MovieMoneyOverTimeCount } from "@/lib/movie-chart-stats";
import { ChartPanel } from "@/components/charts/chart-panel";
import { Button } from "@/components/ui/button";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart";

const chartConfig = {
  budget: {
    label: "Budget",
    color: "var(--chart-2)",
  },
  revenue: {
    label: "Revenue",
    color: "var(--chart-5)",
  },
} satisfies ChartConfig;

type MovieMoneyOverTimeChartProps = {
  monthlyData: MovieMoneyOverTimeCount[];
  yearlyData: MovieMoneyOverTimeCount[];
  monthlyOmittedCount: number;
};

function formatCompactCurrency(value: number) {
  return new Intl.NumberFormat("en", {
    notation: "compact",
    maximumFractionDigits: 1,
    style: "currency",
    currency: "USD",
  }).format(value);
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en", {
    maximumFractionDigits: 0,
    style: "currency",
    currency: "USD",
  }).format(value);
}

export function MovieMoneyOverTimeChart({
  monthlyData,
  yearlyData,
  monthlyOmittedCount,
}: MovieMoneyOverTimeChartProps) {
  const [mode, setMode] = useState<"monthly" | "yearly">("yearly");
  const data = mode === "monthly" ? monthlyData : yearlyData;
  const hasData = data.some((item) => item.budget > 0 || item.revenue > 0);
  const totalBudget = data.reduce((total, item) => total + item.budget, 0);
  const totalRevenue = data.reduce((total, item) => total + item.revenue, 0);

  return (
    <ChartPanel
      title="Budget / Revenue Over Time"
      eyebrow="USD"
      headerContent={
        <div className="flex flex-wrap items-center gap-2">
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div>
              <span className="text-[var(--muted-foreground)]">Budget </span>
              <span className="font-mono tabular-nums text-[var(--foreground)]">
                {formatCompactCurrency(totalBudget)}
              </span>
            </div>
            <div>
              <span className="text-[var(--muted-foreground)]">Revenue </span>
              <span className="font-mono tabular-nums text-[var(--foreground)]">
                {formatCompactCurrency(totalRevenue)}
              </span>
            </div>
          </div>
          <div className="flex">
            <Button
              type="button"
              variant={mode === "monthly" ? "default" : "outline"}
              size="sm"
              className="h-7 rounded-none px-2 text-xs"
              onClick={() => setMode("monthly")}
            >
              Monthly
            </Button>
            <Button
              type="button"
              variant={mode === "yearly" ? "default" : "outline"}
              size="sm"
              className="h-7 rounded-none border-l-0 px-2 text-xs"
              onClick={() => setMode("yearly")}
            >
              Yearly
            </Button>
          </div>
        </div>
      }
    >
      <div className="grid gap-2">
        {mode === "monthly" && monthlyOmittedCount > 0 ? (
          <div className="text-xs text-[var(--muted-foreground)]">
            {monthlyOmittedCount} approximate{" "}
            {monthlyOmittedCount === 1 ? "entry" : "entries"} omitted
          </div>
        ) : null}

        <div className="flex flex-wrap items-center gap-4 text-xs text-[var(--muted-foreground)]">
          <div className="flex items-center gap-1.5">
            <span className="h-0 w-5 border-t-2 border-[var(--chart-2)]" />
            Budget
          </div>
          <div className="flex items-center gap-1.5">
            <span className="h-0 w-5 border-t-2 border-dashed border-[var(--chart-5)]" />
            Revenue
          </div>
        </div>

        {hasData ? (
          <ChartContainer
            config={chartConfig}
            className="h-[260px] w-full aspect-auto"
          >
            <LineChart
              data={data}
              margin={{ top: 8, right: 10, left: 8, bottom: 0 }}
            >
              <CartesianGrid vertical={false} strokeDasharray="2 4" />
              <XAxis
                dataKey="label"
                tickLine={false}
                axisLine={false}
                tickMargin={8}
                interval="preserveStartEnd"
                minTickGap={18}
              />
              <YAxis
                tickLine={false}
                axisLine={false}
                tickFormatter={formatCompactCurrency}
                width={56}
              />
              <ChartTooltip
                cursor={false}
                isAnimationActive={false}
                content={
                  <ChartTooltipContent
                    formatter={(value, name) => (
                      <>
                        <div
                          className="h-2.5 w-2.5 shrink-0 rounded-[2px]"
                          style={{
                            backgroundColor:
                              name === "budget"
                                ? "var(--color-budget)"
                                : "var(--color-revenue)",
                          }}
                        />
                        <span className="text-[var(--muted-foreground)]">
                          {name === "budget" ? "Budget" : "Revenue"}
                        </span>
                        <span className="ml-auto font-mono font-medium tabular-nums text-[var(--foreground)]">
                          {typeof value === "number"
                            ? formatCurrency(value)
                            : String(value)}
                        </span>
                      </>
                    )}
                    labelFormatter={(_, payload) => {
                      const item = payload[0]?.payload as
                        | MovieMoneyOverTimeCount
                        | undefined;

                      return item
                        ? `${item.label} / ${item.movieCount} ${
                            item.movieCount === 1 ? "movie" : "movies"
                          }`
                        : null;
                    }}
                  />
                }
              />
              <Line
                type="monotone"
                dataKey="budget"
                stroke="var(--color-budget)"
                strokeWidth={2}
                dot={false}
                isAnimationActive={false}
              />
              <Line
                type="monotone"
                dataKey="revenue"
                stroke="var(--color-revenue)"
                strokeWidth={2}
                strokeDasharray="4 3"
                dot={false}
                isAnimationActive={false}
              />
            </LineChart>
          </ChartContainer>
        ) : (
          <div className="flex h-[260px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
            No budget or revenue metadata synced yet.
          </div>
        )}
      </div>
    </ChartPanel>
  );
}

// src/components/charts/movie-money-over-time-chart.svelte
<script lang="ts">
  import type { MovieMoneyOverTimeCount } from "@/lib/movie-chart-stats";
  import {
    formatCompactCurrency,
    formatCurrency,
    getLinearTicks,
    getPath,
    shouldShowXAxisLabel,
    type ChartPoint,
    type MoneyDatum,
  } from "./static-chart-utils";

  export let monthlyData: MovieMoneyOverTimeCount[] = [];
  export let yearlyData: MovieMoneyOverTimeCount[] = [];
  export let monthlyOmittedCount = 0;

  let mode: "monthly" | "yearly" = "yearly";
  let pinned: MoneyDatum | null = null;

  const width = 640;
  const height = 260;
  const margin = { top: 8, right: 12, bottom: 30, left: 60 };
  const plotWidth = width - margin.left - margin.right;
  const plotHeight = height - margin.top - margin.bottom;

  $: data = (mode === "monthly" ? monthlyData : yearlyData).map((item) => ({
    key: item.period,
    label: item.label,
    budget: item.budget,
    revenue: item.revenue,
    movieCount: item.movieCount,
  }));
  $: hasData = data.some((item) => item.budget > 0 || item.revenue > 0);
  $: totalBudget = data.reduce((total, item) => total + item.budget, 0);
  $: totalRevenue = data.reduce((total, item) => total + item.revenue, 0);
  $: maxValue = Math.max(...data.flatMap((item) => [item.budget, item.revenue]), 0);
  $: ticks = getLinearTicks(maxValue);
  $: yMax = ticks.at(-1) ?? 1;
  $: stepWidth = data.length > 1 ? plotWidth / (data.length - 1) : plotWidth;

  function point(item: MoneyDatum, index: number, key: "budget" | "revenue"): ChartPoint {
    const x = margin.left + (data.length > 1 ? index * stepWidth : plotWidth / 2);
    const y = margin.top + plotHeight - (yMax > 0 ? (item[key] / yMax) * plotHeight : 0);

    return { x, y };
  }

  $: budgetPath = getPath(data.map((item, index) => point(item, index, "budget")));
  $: revenuePath = getPath(data.map((item, index) => point(item, index, "revenue")));
</script>

<section class="flex flex-col border border-[var(--border)] bg-[var(--card)] p-4">
  <div class="mb-3 flex flex-wrap items-center justify-between gap-3">
    <div class="flex items-baseline gap-3">
      <h2 class="text-sm font-medium">Budget / Revenue Over Time</h2>
      <p class="text-xs tabular-nums text-[var(--muted-foreground)]">USD</p>
    </div>
    <div class="flex flex-wrap items-center gap-2">
      <div class="grid grid-cols-2 gap-2 text-xs">
        <div>
          <span class="text-[var(--muted-foreground)]">Budget </span>
          <span class="font-mono tabular-nums text-[var(--foreground)]">{formatCompactCurrency(totalBudget)}</span>
        </div>
        <div>
          <span class="text-[var(--muted-foreground)]">Revenue </span>
          <span class="font-mono tabular-nums text-[var(--foreground)]">{formatCompactCurrency(totalRevenue)}</span>
        </div>
      </div>
      <div class="flex">
        <button type="button" class={`h-7 border px-2 text-xs ${mode === "monthly" ? "border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-foreground)]" : "border-[var(--border)] bg-[var(--background)]"}`} on:click={() => (mode = "monthly")}>Monthly</button>
        <button type="button" class={`h-7 border border-l-0 px-2 text-xs ${mode === "yearly" ? "border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-foreground)]" : "border-[var(--border)] bg-[var(--background)]"}`} on:click={() => (mode = "yearly")}>Yearly</button>
      </div>
    </div>
  </div>

  <div class="grid gap-2">

  {#if mode === "monthly" && monthlyOmittedCount > 0}
    <div class="text-xs text-[var(--muted-foreground)]">
      {monthlyOmittedCount} approximate {monthlyOmittedCount === 1 ? "entry" : "entries"} omitted
    </div>
  {/if}

  <div class="flex flex-wrap items-center gap-4 text-xs text-[var(--muted-foreground)]">
    <div class="flex items-center gap-1.5"><span class="h-0 w-5 border-t-2 border-[var(--chart-2)]"></span>Budget</div>
    <div class="flex items-center gap-1.5"><span class="h-0 w-5 border-t-2 border-dashed border-[var(--chart-5)]"></span>Revenue</div>
  </div>

  {#if hasData}
    <div class="relative">
      <svg class="h-[260px] w-full overflow-visible" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Budget and revenue over time chart" preserveAspectRatio="none">
        {#each ticks as tick}
          {@const y = margin.top + plotHeight - (yMax > 0 ? (tick / yMax) * plotHeight : 0)}
          <line x1={margin.left} x2={width - margin.right} y1={y} y2={y} stroke="var(--border)" stroke-dasharray="2 4" />
          <text x={margin.left - 8} y={y + 4} text-anchor="end" class="fill-[var(--muted-foreground)] text-[10px] tabular-nums">{formatCompactCurrency(tick)}</text>
        {/each}
        <path d={budgetPath} fill="none" stroke="var(--chart-2)" stroke-width="2" vector-effect="non-scaling-stroke" />
        <path d={revenuePath} fill="none" stroke="var(--chart-5)" stroke-width="2" stroke-dasharray="4 3" vector-effect="non-scaling-stroke" />
        {#each data as item, index}
          {@const budgetPoint = point(item, index, "budget")}
          {@const revenuePoint = point(item, index, "revenue")}
          <g>
            <title>{item.label}: Budget {formatCurrency(item.budget)}, Revenue {formatCurrency(item.revenue)}</title>
            <circle cx={budgetPoint.x} cy={budgetPoint.y} r="5" fill="transparent" class="cursor-pointer" on:click={() => (pinned = item)} />
            <circle cx={revenuePoint.x} cy={revenuePoint.y} r="5" fill="transparent" class="cursor-pointer" on:click={() => (pinned = item)} />
          </g>
          {#if shouldShowXAxisLabel(index, data.length)}
            <text x={budgetPoint.x} y={height - 8} text-anchor="middle" class="fill-[var(--muted-foreground)] text-[10px] tabular-nums">{item.label}</text>
          {/if}
        {/each}
      </svg>
      {#if pinned}
        <div class="absolute right-2 top-2 z-10 min-w-60 max-w-80 border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-xs shadow-lg">
          <div class="flex items-start justify-between gap-3">
            <div>
              <div class="font-medium">{pinned.label} / {pinned.movieCount} {pinned.movieCount === 1 ? "movie" : "movies"}</div>
              <div class="mt-2 grid gap-1 font-mono tabular-nums">
                <div>Budget {formatCurrency(pinned.budget)}</div>
                <div>Revenue {formatCurrency(pinned.revenue)}</div>
              </div>
            </div>
            <button type="button" class="-mr-1 -mt-1 h-7 w-7 border border-transparent text-[var(--muted-foreground)] hover:border-[var(--border)] hover:text-[var(--foreground)]" aria-label="Close pinned tooltip" on:click={() => (pinned = null)}>x</button>
          </div>
        </div>
      {/if}
    </div>
  {:else}
    <div class="flex h-[260px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
      No budget or revenue metadata synced yet.
    </div>
  {/if}
  </div>
</section>
