// src/components/charts/release-year-chart.tsx
"use client";

import { useState } from "react";
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";

import {
  getActiveChartDataIndex,
  MovieListTooltip,
  PinnedMovieListTooltipOverlay,
  type PinnedMovieListTooltip,
} from "@/components/charts/movie-list-tooltip";
import {
  ChartContainer,
  ChartTooltip,
  type ChartConfig,
} from "@/components/ui/chart";
import type { LabelCount } from "@/lib/movie-chart-stats";

const chartConfig = {
  count: {
    label: "Movies",
    color: "var(--chart-4)",
  },
} satisfies ChartConfig;

type ReleaseYearChartProps = {
  data: LabelCount[];
};

type ReleaseYearDatum = LabelCount & {
  year: number;
};

function getYearDomain(data: ReleaseYearDatum[]): [number, number] {
  const years = data.map((item) => item.year);
  const minYear = Math.min(...years);
  const maxYear = Math.max(...years);

  if (minYear === maxYear) {
    return [minYear - 1, maxYear + 1];
  }

  return [minYear, maxYear];
}

export function ReleaseYearChart({ data }: ReleaseYearChartProps) {
  const [pinnedTooltip, setPinnedTooltip] =
    useState<PinnedMovieListTooltip | null>(null);
  const chartData = data
    .map((item) => ({
      ...item,
      year: Number(item.label),
    }))
    .filter((item): item is ReleaseYearDatum => Number.isFinite(item.year));

  if (chartData.length === 0) {
    return (
      <div className="flex h-[260px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
        No release year metadata synced yet.
      </div>
    );
  }

  const yearDomain = getYearDomain(chartData);

  return (
    <div className="relative">
      <ChartContainer
        config={chartConfig}
        className="h-[260px] w-full aspect-auto"
      >
        <BarChart
          data={chartData}
          margin={{ top: 8, right: 8, left: -24, bottom: 0 }}
          onClick={(chartState) => {
            const index = getActiveChartDataIndex(chartState, chartData.length);

            if (index == null) {
              return;
            }

            const item = chartData[index];
            setPinnedTooltip({
              key: item.label,
              title: item.label,
              count: item.count,
              movies: item.movies,
            });
          }}
        >
          <CartesianGrid vertical={false} strokeDasharray="2 4" />
          <XAxis
            dataKey="year"
            type="number"
            scale="linear"
            domain={yearDomain}
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            interval="preserveStartEnd"
            tickFormatter={(year) => String(Math.round(Number(year)))}
          />
          <YAxis allowDecimals={false} tickLine={false} axisLine={false} />
          <ChartTooltip
            active={pinnedTooltip ? false : undefined}
            cursor={false}
            isAnimationActive={false}
            content={
              <MovieListTooltip singularLabel="movie" pluralLabel="movies" />
            }
          />
          <Bar
            dataKey="count"
            fill="var(--color-count)"
            isAnimationActive={false}
            barSize={8}
            radius={[2, 2, 0, 0]}
          />
        </BarChart>
      </ChartContainer>
      <PinnedMovieListTooltipOverlay
        tooltip={pinnedTooltip}
        singularLabel="movie"
        pluralLabel="movies"
        onClose={() => setPinnedTooltip(null)}
      />
    </div>
  );
}

// src/components/charts/release-year-chart.svelte
<script lang="ts">
  import type { LabelCount } from "@/lib/movie-chart-stats";
  import MovieTooltipPanel from "./movie-tooltip-panel.svelte";
  import { getLinearTicks, getRoundedBarPath } from "./static-chart-utils";

  export let data: LabelCount[] = [];

  type TooltipData = LabelCount & {
    x: number;
    y: number;
  };

  let hoverTooltip: TooltipData | null = null;
  let pinnedTooltip: LabelCount | null = null;
  let container: HTMLDivElement;

  const width = 640;
  const height = 260;
  const margin = { top: 8, right: 8, bottom: 30, left: 34 };
  const plotWidth = width - margin.left - margin.right;
  const plotHeight = height - margin.top - margin.bottom;

  $: chartData = data
    .map((item) => ({ key: item.label, label: item.label, count: item.count, movies: item.movies, year: Number(item.label) }))
    .filter((item) => Number.isFinite(item.year))
    .sort((left, right) => left.year - right.year);
  $: maxCount = Math.max(...chartData.map((item) => item.count), 0);
  $: ticks = getLinearTicks(maxCount);
  $: yMax = ticks.at(-1) ?? 1;
  $: minYear = chartData.length > 0 ? Math.min(...chartData.map((item) => item.year)) : 0;
  $: maxYear = chartData.length > 0 ? Math.max(...chartData.map((item) => item.year)) : 0;
  $: domainStart = minYear === maxYear ? minYear - 1 : minYear;
  $: domainEnd = minYear === maxYear ? maxYear + 1 : maxYear;

  function xForYear(year: number) {
    return margin.left + ((year - domainStart) / Math.max(1, domainEnd - domainStart)) * plotWidth;
  }

  function yForCount(count: number) {
    return margin.top + plotHeight - (yMax > 0 ? (count / yMax) * plotHeight : 0);
  }

  function activateTooltip(item: LabelCount, event: PointerEvent) {
    const rect = container.getBoundingClientRect();

    hoverTooltip = {
      ...item,
      x: event.clientX - rect.left,
      y: event.clientY - rect.top,
    };
  }
</script>

{#if chartData.length === 0}
  <div class="flex h-[260px] items-center justify-center border border-dashed border-[var(--border)] text-sm text-[var(--muted-foreground)]">
    No release year metadata synced yet.
  </div>
{:else}
  <div class="relative" bind:this={container} on:pointerleave={() => (hoverTooltip = null)}>
    <svg class="h-[260px] w-full overflow-visible" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Release years chart" preserveAspectRatio="none">
      {#each ticks as tick}
        {@const y = margin.top + plotHeight - (yMax > 0 ? (tick / yMax) * plotHeight : 0)}
        <line x1={margin.left} x2={width - margin.right} y1={y} y2={y} stroke="var(--border)" stroke-dasharray="2 4" />
        <text x={margin.left - 8} y={y + 4} text-anchor="end" class="fill-[var(--muted-foreground)] text-[10px] tabular-nums">{tick}</text>
      {/each}
      {#each chartData as item}
        {@const x = xForYear(item.year)}
        {@const y = yForCount(item.count)}
        <g>
          <title>{item.label}: {item.count.toLocaleString()} {item.count === 1 ? "movie" : "movies"}</title>
          <path
            d={getRoundedBarPath(x - 4, y, 8, margin.top + plotHeight - y)}
            fill="var(--chart-4)"
            class="cursor-pointer opacity-90 hover:opacity-100"
            on:pointerenter={(event) => activateTooltip(item, event)}
            on:pointermove={(event) => activateTooltip(item, event)}
            on:click={() => (pinnedTooltip = item)}
          />
        </g>
      {/each}
      <text x={margin.left} y={height - 8} text-anchor="middle" class="fill-[var(--muted-foreground)] text-[10px] tabular-nums">{domainStart}</text>
      <text x={width - margin.right} y={height - 8} text-anchor="middle" class="fill-[var(--muted-foreground)] text-[10px] tabular-nums">{domainEnd}</text>
    </svg>

    {#if hoverTooltip && !pinnedTooltip}
      <div
        class="pointer-events-none absolute z-10 max-w-[min(20rem,calc(100%-1rem))] -translate-y-[calc(100%+0.5rem)]"
        style={`left: clamp(0.5rem, ${hoverTooltip.x}px, calc(100% - 20rem)); top: ${hoverTooltip.y}px;`}
      >
        <MovieTooltipPanel title={hoverTooltip.label} count={hoverTooltip.count} movies={hoverTooltip.movies} />
      </div>
    {/if}

    {#if pinnedTooltip}
      <div class="absolute right-2 top-2 z-10 max-w-[calc(100%-1rem)]">
        <MovieTooltipPanel
          title={pinnedTooltip.label}
          count={pinnedTooltip.count}
          movies={pinnedTooltip.movies}
          pinned
          onClose={() => (pinnedTooltip = null)}
        />
      </div>
    {/if}
  </div>
{/if}
